### ISSUE TITLE
Lift ClauseId to a struct

### ISSUE THREAD

**Issue by shnarazk** [shnarazk/splr#1]
### Purpose

another refactoring on ClauseId which is an alias of `usize`

### Todo

- [x] no performance regression
- [x] make fields private
- [x] ~~refactor exporting/importing symbols~~ *Changing relations affects performance somehow.*

- before

```
solver,       num,                 target,    time
"splr",         1,           "UF250(100)", 103.478
"splr",         3,          "UUF250(100)", 356.468 
```

- after inlining

```
"splr",         1,           "UF250(100)", 103.600
"splr",         2,          "UUF250(100)", 356.598
```

**Comment by shnarazk** [comment]
A memo

- fixed var decay: 0.94

```
solver,       num,                 target,    time
"splr",         1,           "UF250(100)", 110.310
"splr",         2,          "UUF250(100)", 366.395
"splr",         3, "3/SAT/v360-c1530/002",  58.694
"splr",         4, "3/SAT/v360-c1530/030",  68.794
"splr",         5, "3/SAT/v360-c1530/033",   5.007
"splr",         6, "3/SAT/v360-c1530/035",   1.982
"splr",         7, "3/SAT/v360-c1530/039",   ABORT
"splr",         8, "3/SAT/v360-c1530/051", 378.226
"splr",         9, "3/SAT/v360-c1530/060", 382.024
"splr",        10, "3/SAT/v360-c1530/073", 144.219
"splr",        11, "3/SAT/v360-c1530/087",   6.545
"splr",        12, "3/SAT/v360-c1530/093",  14.747
"splr",        13, "3/UNS/v360-c1530/001", 391.533
"splr",        14, "3/UNS/v360-c1530/015", 318.427
"splr",        15, "3/UNS/v360-c1530/028", 383.842
"splr",        16, "3/UNS/v360-c1530/029",   ABORT
"splr",        17, "3/UNS/v360-c1530/031", 484.622
"splr",        18, "3/UNS/v360-c1530/053", 407.395
"splr",        19, "3/UNS/v360-c1530/061",   ABORT
"splr",        20, "3/UNS/v360-c1530/086", 217.996
"splr",        21, "3/UNS/v360-c1530/089", 299.080
"splr",        22, "3/UNS/v360-c1530/096", 207.064
"splr",        23,          "SR2015/itox",   1.632
"splr",        24,          "SR2015/m283",  25.953
"splr",        25,           "SR2015/38b",  20.845
"splr",        26,           "SR2015/44b",  67.996
```
